services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: xweeter_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 3s

  app:
    container_name: elixir_web_app
    build:
      context: .
      dockerfile: app.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DATABASE_URL: "ecto://postgres:postgres@db/xweeter_dev"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: xweeter_dev
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:4000/ || exit 1"]
      interval: 5s
      retries: 10
      timeout: 5s

volumes:
  postgres_data:
